# Generated by Django 4.2.28 on 2026-02-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=45000, max_digits=10),
            preserve_default=False,
        ),
    ]
