# Generated by Django 4.2.28 on 2026-02-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_nights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='nights',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
